#**Tech Stack Recommender**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import requests
import io

import re
from urllib.parse import urlparse, parse_qs, unquote

%matplotlib inline

In [ ]:
url = "https://raw.githubusercontent.com/mikeasilva/data-scientist-skills/master/raw_skills.csv"
r = requests.get(url)

try:
  df = pd.read_csv(io.StringIO(r.text))
  items = df['raw_skills'].dropna().astype(str).tolist()
except Exception as e:
  print(f"Error reading CSV: {e}")

df.head(20)

,id,raw_skills,url
0,1,"['natural language', ' artificial intelligence...",https://www.dice.com/jobs/detail/Data-Scientis...
1,2,"['analyst', ' database', ' developer', ' infor...",https://www.dice.com/jobs/detail/Data-Engineer...
2,3,"['data analytics', ' data mining and statistic...",https://www.dice.com/jobs/detail/Data-Scientis...
3,4,"['data science', ' machine learning', ' python...",https://www.dice.com/jobs/detail/Senior-Data-S...
4,5,"['analysis', ' change management', ' consultin...",https://www.dice.com/jobs/detail/Data-Scientis...
5,6,"['machine learning', ' python', ' natural lang...",https://www.dice.com/jobs/detail/Natural-Langu...
6,7,"['architect', ' cloud', ' business intelligenc...",https://www.dice.com/jobs/detail/Cloud-Computi...
7,8,"['algorithms', ' analysis', ' data mining', ' ...",https://www.dice.com/jobs/detail/Sr.-Data-Scie...
8,9,"['analysis', ' architecture', ' benchmark', ' ...",https://www.dice.com/jobs/detail/DATA-SCIENTIS...
9,10,['masters degree with 5 years of experience in...,https://www.dice.com/jobs/detail/Data-Scientis...
10,11,[''],https://www.dice.com/jobs/detail/Senior-Data-S...
11,12,['n/a'],https://www.dice.com/jobs/detail/Data-Scientis...
12,13,"['algorithms', ' analysis', ' business require...",https://www.dice.com/jobs/detail/Cyber-Securit...
13,14,"['database', ' management', ' python', ' sql']",https://www.dice.com/jobs/detail/Data-Scientis...
14,15,['data scientist'],https://www.dice.com/jobs/detail/Data-scientis...
15,16,"['data science', ' statistics', ' machine lear...",https://www.dice.com/jobs/detail/Data-Scientis...
16,17,[''],https://www.dice.com/jobs/detail/Data-Scientis...
17,18,"['data scientist', ' python', ' clustering alg...",https://www.dice.com/jobs/detail/Data-Scientis...
18,19,"['sme in statistics', ' analytics', ' big data...",https://www.dice.com/jobs/detail/Data-scientis...
19,20,[''],https://www.dice.com/jobs/detail/Associate-Dir...

In [ ]:
invalid_values = ["['']", "['n/a']", "[]"]
df = df[~df['raw_skills'].isin(invalid_values)]
df.dropna(subset=['raw_skills'], inplace=True)
df.drop('id', axis=1, inplace=True)
df.head(10)

,raw_skills,url
0,"['natural language', ' artificial intelligence...",https://www.dice.com/jobs/detail/Data-Scientis...
1,"['analyst', ' database', ' developer', ' infor...",https://www.dice.com/jobs/detail/Data-Engineer...
2,"['data analytics', ' data mining and statistic...",https://www.dice.com/jobs/detail/Data-Scientis...
3,"['data science', ' machine learning', ' python...",https://www.dice.com/jobs/detail/Senior-Data-S...
4,"['analysis', ' change management', ' consultin...",https://www.dice.com/jobs/detail/Data-Scientis...
5,"['machine learning', ' python', ' natural lang...",https://www.dice.com/jobs/detail/Natural-Langu...
6,"['architect', ' cloud', ' business intelligenc...",https://www.dice.com/jobs/detail/Cloud-Computi...
7,"['algorithms', ' analysis', ' data mining', ' ...",https://www.dice.com/jobs/detail/Sr.-Data-Scie...
8,"['analysis', ' architecture', ' benchmark', ' ...",https://www.dice.com/jobs/detail/DATA-SCIENTIS...
9,['masters degree with 5 years of experience in...,https://www.dice.com/jobs/detail/Data-Scientis...

In [ ]:
def extract_job_title(url_string):
  url_string = str(url_string)
  url_string = unquote(url_string)

  parsed_url =  urlparse(url_string)
  query_params = parse_qs(parsed_url.query)

  for key in ['q', 'query', 'job', 'title']:
    if key in query_params:
      if key in query_params:
            clean_text = query_params[key][0]
            return clean_text.title()

    last_part = parsed_url.path.strip('/').split('/')[-1]

    clean_text = re.sub(r'[^a-zA-Z]', ' ', last_part)

    clean_text = ' '.join(clean_text.split()).title()

    return clean_text

df['job_title'] = df['url'].apply(extract_job_title)

# 4. Now you can safely drop the messy URL column if you want
df.drop(columns=["url"], inplace=True)

# Display the first 5 rows to verify it worked!
df.head(10)

,raw_skills,job_title
0,"['natural language', ' artificial intelligence...",Data Scientist
1,"['analyst', ' database', ' developer', ' infor...","""Data Scientist"""
2,"['data analytics', ' data mining and statistic...","""Data Scientist"""
3,"['data science', ' machine learning', ' python...",Cg
4,"['analysis', ' change management', ' consultin...",Data Scientist Python
5,"['machine learning', ' python', ' natural lang...",Sm
6,"['architect', ' cloud', ' business intelligenc...",Cloud Computing Architect
7,"['algorithms', ' analysis', ' data mining', ' ...",Sr Data Scientist
8,"['analysis', ' architecture', ' benchmark', ' ...",E Bf
9,['masters degree with 5 years of experience in...,"""Data Scientist"""

In [ ]:
df.dropna(subset=['raw_skills'], inplace=True)
df.head(10)

,raw_skills,job_title
0,"['natural language', ' artificial intelligence...",Data Scientist
1,"['analyst', ' database', ' developer', ' infor...","""Data Scientist"""
2,"['data analytics', ' data mining and statistic...","""Data Scientist"""
3,"['data science', ' machine learning', ' python...",Cg
4,"['analysis', ' change management', ' consultin...",Data Scientist Python
5,"['machine learning', ' python', ' natural lang...",Sm
6,"['architect', ' cloud', ' business intelligenc...",Cloud Computing Architect
7,"['algorithms', ' analysis', ' data mining', ' ...",Sr Data Scientist
8,"['analysis', ' architecture', ' benchmark', ' ...",E Bf
9,['masters degree with 5 years of experience in...,"""Data Scientist"""

In [ ]:
df.dropna(subset=['job_title'], inplace=True)

df = df[df['job_title'].str.len() >= 6]

df = df.reset_index(drop=True)

print(f"Dataset loaded and cleaned! Total valid rows: {len(df)}")
df.head(10)

Dataset loaded and cleaned! Total valid rows: 305

,raw_skills,job_title
0,"['natural language', ' artificial intelligence...",Data Scientist
1,"['analyst', ' database', ' developer', ' infor...","""Data Scientist"""
2,"['data analytics', ' data mining and statistic...","""Data Scientist"""
3,"['analysis', ' change management', ' consultin...",Data Scientist Python
4,"['architect', ' cloud', ' business intelligenc...",Cloud Computing Architect
5,"['algorithms', ' analysis', ' data mining', ' ...",Sr Data Scientist
6,['masters degree with 5 years of experience in...,"""Data Scientist"""
7,"['database', ' management', ' python', ' sql']","""Data Scientist"""
8,"['data science', ' statistics', ' machine lear...",Data Scientist
9,"['sme in statistics', ' analytics', ' big data...","""Data Scientist"""

In [ ]:
print("="*10)
print("Provide at least 3 technical skills")
user_input = input("Enter your skills (comma-separated): ")

==========
Provide at least 3 technical skills
Enter your skills (comma-separated):  business intelligence,  development, hadoop, java

In [ ]:
if not user_input.strip():
  print("\n[COLD START DETECTED]: No user profile data found.")
  print("Bypassing similarity math.")
  print("Recommended Career Paths:")

  trending = df['raw_skills'].value_counts().head(3)
  print(trending)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer()

item_vectors = vectorizer.fit_transform(df['raw_skills'])
user_vector = vectorizer.transform([user_input])

similarity_scores = cosine_similarity(user_vector, item_vectors)
print("Similarity Scores:", similarity_scores)

Similarity Scores: [[0.167259   0.         0.         0.06647791 0.24931665 0.
  0.         0.         0.10516233 0.         0.03221345 0.04388347
  0.12555209 0.         0.21195349 0.27194724 0.04937898 0.
  0.19194065 0.14725144 0.09993588 0.         0.21764153 0.
  0.         0.12442531 0.         0.05050398 0.         0.21104237
  0.07373432 0.24534707 0.         0.         0.05053685 0.
  0.         0.         0.         0.         0.14181262 0.05220351
  0.         0.33821912 0.         0.08148165 0.         0.21779034
  0.         0.24175648 0.09522359 0.         0.         0.52524345
  0.         0.         0.         0.20581624 0.         0.04975995
  0.10825974 0.         0.         0.         0.         0.15167845
  0.         0.         0.         0.04644346 0.         0.
  0.         0.         0.09087767 0.         0.13763114 0.20581624
  0.20401526 0.         0.10781691 0.35572666 0.         0.
  0.22108081 0.         0.12442531 0.         0.         0.
  0.         0.06490693 0.         0.06789101 0.0643644  0.12314652
  0.20867403 0.         0.1081418  0.19769928 0.19717859 0.18082002
  0.11431993 0.         0.         0.         0.         0.
  0.16885545 0.26675822 0.         0.         0.         0.20581624
  0.32354124 0.16117377 0.06383322 0.07120411 0.23364867 0.11116759
  0.07725018 0.         0.         0.         0.         0.
  0.14371618 0.12187401 0.2923106  0.17176799 0.         0.
  0.         0.1017551  0.         0.0803223  0.1929496  0.05000957
  0.         0.         0.         0.         0.         0.
  0.07970709 0.04760915 0.09085987 0.         0.         0.
  0.09341466 0.05053685 0.09936507 0.09871615 0.         0.09512745
  0.14318437 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.18046798
  0.25586637 0.16905814 0.         0.22137341 0.03330691 0.
  0.         0.09655616 0.         0.         0.06326039 0.
  0.         0.         0.         0.         0.06955711 0.
  0.         0.         0.         0.         0.         0.10412261
  0.         0.         0.12090251 0.07038295 0.11947722 0.14233676
  0.07554949 0.         0.         0.         0.09530202 0.
  0.         0.14511271 0.05458253 0.         0.         0.
  0.21958852 0.         0.         0.15996218 0.         0.15404686
  0.11783606 0.2077921  0.09138636 0.11065957 0.         0.
  0.07312543 0.         0.         0.098462   0.         0.
  0.         0.07291134 0.         0.11030765 0.09757522 0.
  0.10757787 0.07945598 0.         0.         0.         0.
  0.         0.         0.1235038  0.07152349 0.09772866 0.
  0.         0.         0.         0.17067125 0.1366133  0.13576951
  0.08445628 0.15391384 0.         0.         0.18187415 0.29042059
  0.25962114 0.         0.         0.         0.         0.09341466
  0.05543134 0.         0.         0.         0.         0.19111461
  0.         0.         0.         0.21157918 0.16411353 0.23136584
  0.1393592  0.13044376 0.         0.         0.25729853 0.
  0.21709083 0.11914483 0.21181845 0.         0.         0.
  0.22259857 0.         0.         0.         0.20888372 0.12795356
  0.07059412 0.         0.         0.         0.12007387 0.
  0.48224536 0.         0.         0.         0.        ]]

In [ ]:
job_titles = ["Data Scientist", "DevOps Engineer", "Backend Developer"]

scores = similarity_scores.flatten()

sorted_indices = scores.argsort()[::-1]
top_n = 3

top_n_indices = sorted_indices[:top_n]

print(f"--- Top {top_n} Recommended Career Paths ---")
for index in top_n_indices:
    career_path = df['job_title'].iloc[index]
    matched_skills = df['raw_skills'].iloc[index]
    score = scores[index]

    print(f"Match Score: {score * 100:.1f}%")
    print(f"Recommended Role: {career_path}")
    print(f"Required Skills: {matched_skills}\n")

--- Top 3 Recommended Career Paths ---
Match Score: 52.5%
Recommended Role: "Data Scientist"
Required Skills: ['automated', ' business intelligence', ' development', ' hadoop', ' java', ' modeling', ' physics', ' programming', ' project', ' python', ' research', ' sas', ' sales', ' sql', ' testing']

Match Score: 48.2%
Recommended Role: "Data Scientist"
Required Skills: ['analysis', ' business intelligence', ' business requirements', ' data collection', ' hadoop', ' java', ' management', ' metrics', ' nosql', ' project', ' python', ' sql', ' supply chain']

Match Score: 35.6%
Recommended Role: "Data Scientist"
Required Skills: ['algorithms', ' analysis', ' artificial intelligence', ' business objects', ' data analysis', ' data mining', ' development', ' director', ' environmental', ' hadoop', ' java', ' javascript', ' modeling', ' mysql', ' mysql', ' networks', ' python', ' sas', ' simulation', ' sql', ' testing']